package controllers;

public enum ActionCommands {
	NEXT_IMAGE, PREVIOUS_IMAGE,
	DBZ_IMAGE,DEATH_NOTE_IMAGE,NARUTO_IMAGE ,SHINGEKY_NO_KYOJIN_IMAGE
	,ONE_PIECE_IMAGE ,NANATSU_NO_TAIZAI_IMAGE, ONE_PUNCH_MAN_IMAGE;
}
