package controllers;

public enum Commands {
<<<<<<< HEAD
	CHANGE_ENGLISH, CHANGE_SPANISH,OPEN_LENGUAGE_DIALOG,EXIT,TABLE_REPORTS,PANEL_INITIAL,GRAPHIC_REPORTS;
=======
	CHANGE_ENGLISH, CHANGE_SPANISH,OPEN_LENGUAGE_DIALOG,EXIT,TABLE_CULTIVES, GRAFICA;
>>>>>>> 23db6bbe654164f766c1e03100086c5d3e0f00b0
}
