package controllers;

public enum Commands {
	CHANGE_ENGLISH, CHANGE_SPANISH,OPEN_LENGUAGE_DIALOG,EXIT,TABLE_REPORTS,PANEL_INITIAL,GRAPHIC_REPORTS,
<<<<<<< HEAD
	REPORT_EIGHT,REPORT_NINE,REPORT_TEN,GRAPHIC_REPORT_ONE;
=======
	REPORT_EIGHT,REPORT_NINE,REPORT_TEN, GRAPHIC_REPORT_ONE;
>>>>>>> ca063f8df7da0a61d1d699f32ed89369078ad8f9
}
