package controllers;

public enum Commands {
<<<<<<< HEAD
	CHANGE_ENGLISH, CHANGE_SPANISH,OPEN_LENGUAGE_DIALOG,EXIT,TABLE_REPORTS,PANEL_INITIAL,GRAPHIC_REPORTS,
	REPORT_EIGHT,REPORT_NINE,REPORT_TEN;
=======
	CHANGE_ENGLISH, CHANGE_SPANISH,OPEN_LENGUAGE_DIALOG,EXIT,TABLE_REPORTS,PANEL_INITIAL,GRAPHIC_REPORTS, GRAPHIC_REPORT_ONE;
>>>>>>> f4e8d4ab5e803473169d034f3bdef0c52390d149
}
